{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPe+YGyvJDbtoVEm9Bgy6bH",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/tiaradwiwulandari745-glitch/TUGAS-DASBORD/blob/main/CODING%20DASBORD.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "OHmDpLVkY_01"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "\n",
        "st.set_page_config(page_title=\"Dashboard Analisis Evaluasi\", layout=\"wide\")\n",
        "\n",
        "st.title(\"📊 Dashboard Analisis Evaluasi Pembelajaran\")\n",
        "st.write(\"Data: 50 Siswa - 20 Soal\")\n",
        "\n",
        "# =========================\n",
        "# LOAD DATA\n",
        "# =========================\n",
        "@st.cache_data\n",
        "def load_data():\n",
        "    return pd.read_excel(\"data_simulasi_50_siswa_20_soal.xlsx\")\n",
        "\n",
        "df = load_data()\n",
        "\n",
        "# Ambil 20 kolom soal pertama\n",
        "soal = df.iloc[:, :20]\n",
        "\n",
        "df[\"Total_Skor\"] = soal.sum(axis=1)\n",
        "df[\"Rata_Rata\"] = soal.mean(axis=1)\n",
        "\n",
        "# =========================\n",
        "# 1. DESKRIPSI DESKRIPTIF\n",
        "# =========================\n",
        "st.header(\"1️⃣ Statistik Deskriptif\")\n",
        "\n",
        "col1, col2, col3 = st.columns(3)\n",
        "col1.metric(\"Jumlah Siswa\", len(df))\n",
        "col2.metric(\"Rata-rata Total Skor\", round(df[\"Total_Skor\"].mean(),2))\n",
        "col3.metric(\"Standar Deviasi\", round(df[\"Total_Skor\"].std(),2))\n",
        "\n",
        "fig1 = plt.figure()\n",
        "plt.hist(df[\"Total_Skor\"], bins=10)\n",
        "plt.xlabel(\"Total Skor\")\n",
        "plt.ylabel(\"Frekuensi\")\n",
        "st.pyplot(fig1)\n",
        "\n",
        "# =========================\n",
        "# 2. ANALISIS PER SOAL\n",
        "# =========================\n",
        "st.header(\"2️⃣ Analisis Per Soal\")\n",
        "\n",
        "rata_soal = soal.mean()\n",
        "std_soal = soal.std()\n",
        "\n",
        "analisis_soal = pd.DataFrame({\n",
        "    \"Rata-rata\": rata_soal,\n",
        "    \"Standar Deviasi\": std_soal\n",
        "})\n",
        "\n",
        "st.dataframe(analisis_soal)\n",
        "\n",
        "fig2 = plt.figure()\n",
        "rata_soal.plot(kind=\"bar\")\n",
        "plt.xlabel(\"Soal\")\n",
        "plt.ylabel(\"Rata-rata Skor\")\n",
        "st.pyplot(fig2)\n",
        "\n",
        "# =========================\n",
        "# 3. SOAL TERBAIK & TERBURUK\n",
        "# =========================\n",
        "st.header(\"3️⃣ Soal Terbaik & Terburuk\")\n",
        "\n",
        "soal_terbaik = rata_soal.idxmax()\n",
        "soal_terburuk = rata_soal.idxmin()\n",
        "\n",
        "st.success(f\"Soal Termudah: {soal_terbaik}\")\n",
        "st.error(f\"Soal Tersulit: {soal_terburuk}\")\n",
        "\n",
        "# =========================\n",
        "# 4. ANALISIS GAP\n",
        "# =========================\n",
        "st.header(\"4️⃣ Analisis GAP\")\n",
        "\n",
        "nilai_maks = soal.max().max()\n",
        "gap = nilai_maks - rata_soal\n",
        "\n",
        "gap_df = pd.DataFrame({\"GAP\": gap})\n",
        "st.dataframe(gap_df)\n",
        "\n",
        "fig3 = plt.figure()\n",
        "gap.plot(kind=\"bar\")\n",
        "plt.xlabel(\"Soal\")\n",
        "plt.ylabel(\"GAP terhadap skor maksimum\")\n",
        "st.pyplot(fig3)\n",
        "\n",
        "# =========================\n",
        "# 5. SEGMENTASI SISWA\n",
        "# =========================\n",
        "st.header(\"5️⃣ Segmentasi Siswa\")\n",
        "\n",
        "mean_total = df[\"Total_Skor\"].mean()\n",
        "std_total = df[\"Total_Skor\"].std()\n",
        "\n",
        "def kategori(skor):\n",
        "    if skor >= mean_total + std_total:\n",
        "        return \"Tinggi\"\n",
        "    elif skor >= mean_total:\n",
        "        return \"Sedang\"\n",
        "    else:\n",
        "        return \"Rendah\"\n",
        "\n",
        "df[\"Kategori\"] = df[\"Total_Skor\"].apply(kategori)\n",
        "\n",
        "segmentasi = df[\"Kategori\"].value_counts()\n",
        "st.dataframe(segmentasi)\n",
        "\n",
        "fig4 = plt.figure()\n",
        "segmentasi.plot(kind=\"bar\")\n",
        "plt.xlabel(\"Kategori\")\n",
        "plt.ylabel(\"Jumlah Siswa\")\n",
        "st.pyplot(fig4)\n",
        "\n",
        "# =========================\n",
        "# 6. KORELASI\n",
        "# =========================\n",
        "st.header(\"6️⃣ Korelasi Antar Soal\")\n",
        "\n",
        "corr_matrix = soal.corr()\n",
        "\n",
        "fig5 = plt.figure()\n",
        "plt.imshow(corr_matrix)\n",
        "plt.colorbar()\n",
        "plt.title(\"Matriks Korelasi\")\n",
        "st.pyplot(fig5)\n",
        "\n",
        "# =========================\n",
        "# 7. KESIMPULAN OTOMATIS\n",
        "# =========================\n",
        "st.header(\"7️⃣ Kesimpulan\")\n",
        "\n",
        "rata_total = df[\"Total_Skor\"].mean()\n",
        "\n",
        "if rata_total > (nilai_maks * 20 * 0.7):\n",
        "    tingkat = \"TINGGI\"\n",
        "elif rata_total > (nilai_maks * 20 * 0.5):\n",
        "    tingkat = \"SEDANG\"\n",
        "else:\n",
        "    tingkat = \"RENDAH\"\n",
        "\n",
        "st.write(f\"\"\"\n",
        "Rata-rata total skor siswa adalah {round(rata_total,2)}.\n",
        "Secara umum tingkat pencapaian berada pada kategori {tingkat}.\n",
        "Soal termudah adalah {soal_terbaik}, sedangkan soal tersulit adalah {soal_terburuk}.\n",
        "Distribusi segmentasi menunjukkan variasi performa siswa.\n",
        "Korelasi antar soal menunjukkan adanya keterkaitan antar indikator kompetensi.\n",
        "\"\"\")\n",
        "\n",
        "st.divider()\n",
        "st.subheader(\"Data Lengkap\")\n",
        "st.dataframe(df)"
      ]
    }
  ]
}